# Generated by Django 4.2.23 on 2025-08-17 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['-created_at', 'id']},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-created_at', 'id']},
        ),
    ]
