# Generated by Django 4.2.23 on 2025-08-18 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('common', '0001_initial'),
        ('clubs', '0002_alter_plan_options_alter_subscription_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={},
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='created_at',
            new_name='starts_at',
        ),
        migrations.AlterUniqueTogether(
            name='plan',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='cancel_at_period_end',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='current_period_end',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='current_period_start',
        ),
        migrations.AddField(
            model_name='plan',
            name='name',
            field=models.CharField(default='Unnamed plan', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='project',
            field=models.ForeignKey(
                to='projects.project',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='plans',
                null=True, blank=True,  # <- делаем временно nullable!
            ),
        ),

        migrations.AddField(
            model_name='subscription',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(default='active', max_length=16),
        ),
        migrations.CreateModel(
            name='PlanChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_plans', to='common.telegramchat')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_channels', to='clubs.plan')),
            ],
            options={
                'unique_together': {('plan', 'chat')},
            },
        ),
        migrations.RemoveField(
            model_name='plan',
            name='club',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='period',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='title',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='trial_days',
        ),
        migrations.AddField(
            model_name='plan',
            name='channels',
            field=models.ManyToManyField(blank=True, related_name='plans', through='clubs.PlanChannel', to='common.telegramchat'),
        ),
    ]
