# Generated by Django 4.2.23 on 2025-08-26 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('clubs', '0003_alter_plan_options_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='projects.project'),
            preserve_default=False,
        ),
    ]
