# Generated by Django 4.2.23 on 2025-08-26 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramchat',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='telegramchat',
            name='tg_chat_id',
        ),
        migrations.RemoveField(
            model_name='telegramchat',
            name='verified_at',
        ),
        migrations.AddField(
            model_name='telegramchat',
            name='added_by',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramchat',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('pending_rights', 'Требуются права'), ('inactive', 'Неактивен')], default='pending_rights', max_length=32),
        ),
        migrations.AddField(
            model_name='telegramchat',
            name='tg_id',
            field=models.BigIntegerField(db_index=True, default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telegramchat',
            name='username',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='telegramchat',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='telegramchat',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_chats', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='telegramchat',
            name='title',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='telegramchat',
            name='type',
            field=models.CharField(choices=[('channel', 'Channel'), ('supergroup', 'Supergroup'), ('group', 'Group'), ('private', 'Private')], max_length=32),
        ),
        migrations.CreateModel(
            name='ChatLinkIntent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('tg_user_id', models.BigIntegerField(blank=True, null=True)),
                ('tg_request_id', models.BigIntegerField(blank=True, null=True)),
                ('chat_id', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('consumed', 'Использовано'), ('expired', 'Просрочено'), ('cancelled', 'Отменено')], default='pending', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_intents', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_intents', to='projects.project')),
            ],
        ),
    ]
